server:
  port: 8081

spring:
  application:
    name: blockChain
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://scohe.tpddns.cn:13306/dfsl_iroms_test?useUnicode=true&characterEncoding=utf-8
    username: iroms_test_user
    password: yLiSkG4Ljs0bH%I#
  jpa:
    database: mysql
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
